- examples/README.md
Change `kubectl apply -f echoserver-ingress-notls.yaml` to `kubectl apply -f echoserver-ingress-tls.yaml`
I believe this is the proper ingress file to apply under this header?
> Set to proper file name for Enable tls for echoserver ingress in README

- Dockerfile
- Jenkinsfile
- Makefile
- README.md
Hi Jetstack folks! You might have heard we're working with some folks in the container community on a [standard label schema](http://label-schema.org), and a tool called [MicroBadger](microbadger.com) that lets you inspect image metadata and get badges for your GitHub and Docker Hub pages. 
To get momentum we want to encourage as many people as possible to label their public container images. Here's a PR that will label your image automatically as part of your existing build process.
I will fess up that I have not tested the Jenkins build change but I guess we'll see what happens in the automated build when I submit this PR :-) 
Was nice to see Matt at AWS last week!
> Add some labels and a badge linking to image on Docker Hub

- pkg/acme/cert_request.go
I was running into a loop where the certificate would be requested repeatedly and then I would get rate limiting error before finding out what the error with the certificate was.
This way the errors from ACME are logged.
```
2016/08/16 20:31:54 [INFO][example.com] acme: Obtaining bundled SAN certificate
2016/08/16 20:31:55 [INFO][example.com] acme: Could not find solver for: tls-sni-01
2016/08/16 20:31:55 [INFO][example.com] acme: Could not find solver for: dns-01
2016/08/16 20:31:55 [INFO][example.com] acme: Trying to solve HTTP-01
2016/08/16 20:31:55 [INFO][example.com] The server validated our request
2016/08/16 20:31:55 [INFO][example.com] acme: Validations succeeded; requesting certificates
time="2016-08-16T20:31:58Z" level=debug msg="testing reachablity of …
```
> ObtainCert: Add error logging to retry loop

- pkg/acme/cert_request.go
- pkg/ingress/ingress.go
- pkg/ingress/tls_suite_test.go
- pkg/kubelego/configure.go
- pkg/kubelego/kubelego.go
- pkg/mocks/ingress.go
- pkg/provider/gce/gce.go
- pkg/provider/gce/gce_suite_test.go
- pkg/provider/nginx/nginx.go
- pkg/secret/secret.go
- pkg/service/service.go
This commit just fixes a few typos / inconsistencies in log message strings and should have no other impact. The only exception is the fix in`pkg/mocks/ingress.go` (probably didn't work before ?)
> Fixing a few typos

- README.md
It is easier to read when inside the folder than just seeing the readme as this readme refers to files in the folder.
> Better links for full deployment examples

- Dockerfile
Fix kube-lego crashing #71 
Same as https://github.com/funktionio/funktion/pull/32
The image size just increased 4MB
```
kube-lego-alpine                                  latest              ea7ca4b996df        11 hours ago        65 MB
kube-lego-scratch                                 latest              36e6953dc0f6        12 hours ago        61 MB
```
> change image to alpine

- README.md
- pkg/kubelego/kubelego.go
- pkg/kubelego_const/consts.go
This enables kube-lego to watch its configured annotation and getting certificate from corresponding LE provider.
For running with staging LE, the annotation can be the default one or `kubernetes.io/tls-acme-staging` and for production `kubernetes.io/tls-acme-production`. This will avoid people running into unnecessary LE rate limit by avoiding asking for certs from production until they really need it.
This will close #50
> add support for running multiple instance of kube-lego in the cluster

- README.md
- pkg/ingress/ingress.go
- pkg/ingress/ingress_test.go
- pkg/kubelego/kubelego.go
- pkg/kubelego/type.go
- pkg/kubelego_const/interfaces.go
- pkg/mocks/mocks.go
- pkg/provider/nginx/nginx.go
I'm restricting my ingresses to internal and external traffic. To do this, I'm running 2 ingress with  [ingress--class] (https://github.com/kubernetes/ingress/blob/6cd21f7dea61e4df694d62857d5ea31f442962ce/core/pkg/ingress/controller/launch.go#L43) option.
When I finished the setup, I realise that kube-lego start ignoring my certificates with this message below.
```
time="2017-03-07T14:59:21Z" level=info msg="ignoring as unsupported ingress class 'intern'" context=ingress name=kibana namespace=log
```
This PR add the ability to kube-lego to work with different class (default: nginx,gce).
Ex:
```LEGO_SUPPORTED_INGRESS_CLASS="intern,extern,nginx,custom"```
> Add ability to customize ingress class

- README.md
- pkg/ingress/ingress.go
- pkg/kubelego/kubelego.go
- pkg/kubelego/type.go
- pkg/kubelego/watch.go
- pkg/kubelego_const/interfaces.go
- pkg/mocks/kubelego.go
- pkg/mocks/mocks.go
When the LEGO_WATCH_NAMESPACE environment variable is set to a non-empty value then kube-lego
will only monitor that namespace rather than all namespaces.
> Add ability to only monitor a single namespace

- Makefile
This allows us to create our own patched builds easily:
```sh
make DOCKER_IMAGE=...our-repository-url.../kube-lego push
```
> Actually use the DOCKER_IMAGE variable

- pkg/kubelego/kubelego.go
Before this fix AnnotationEnabled would be set to the empty string,
causing kube-lego to ignore all events.
> fix logic typo

- main.go
kube-lego doesn't have arguments, but doing the parsing here allows to enable
flags for imported packages (such as enabling logging of the kubernetes client!)
> Parse any command line arguments using flag.Parse

- pkg/kubelego/configure_test.go
- pkg/kubelego/kubelego.go
- pkg/kubelego/type.go
KubeLego's Log() function used to get and parse the LEGO_LOG_LEVEL environment
variable for every call, and then create an instance with the correct context set.
This is highly useless: environment variables should never change while a program
is running.
> Configure the log.Entry instance once

- Dockerfile
This makes it possible to just provide arguments to kube-lego, rather than having
to know where in the image the binary actually is.
> Set the ENTRYPOINT instead of the CMD

- pkg/acme/cert_request.go
This should solve these errors:
> Required value, data[tls.key]: Required value]" context=kubelego
> Fix suppressed error while ACME client creation

- README.md
1. Remove details about deployment.yaml et al
2. Link directly to GCE/nginx example README
3. Keep the bit about looking ag LE staging by default
fixes #157 
fixes #158
If this is merged, PR #166 should be closed and ignored.
> Change text under "run kube-lego"

- pkg/secret/secret.go
1. Change original message to "attempting" to create a secret
2. Add a log in the Save() method so that we log when the save action
actually occurred
fixes #161
> Tweak log messages when creating secrets

- examples/gce/echoserver/ingress-notls.yaml
- examples/gce/echoserver/ingress-tls.yaml
Without this, paths outside the root such as `/foo` point to the default backend. Fixes #115.
> Change ingress paths from / to /* in gce example

- pkg/kubelego/configure.go
This makes the warning message less confusing by using the typical
order of namespace/name rather than name/namespace.
> Fix the order of namespace/name in the secret names

- pkg/ingress/ingress.go
This error message currently reports that there was an error while
getting "secret", but it should actually state that it failed to
get an "ingress."
> correct wording when failing to get ingress

- pkg/ingress/ingress.go
- pkg/kubelego_const/consts.go
- pkg/provider/nginx/nginx.go
whitelist all ips for acme http challenge path
fix #203
> whitelist ingress ip source range

- pkg/kubelego/watch.go
https://github.com/jetstack/kube-lego/issues/137
> break up infinite update loop #137

- README.md
- pkg/kubelego/kubelego.go
Adds ability to change logformat in logrus.`json` is super useful for people using eg. Splunk or Logstash.
Configuration stanza is the default from https://github.com/sirupsen/logrus/blob/3d4380f53a34dcdc95f0c1db702615992b38d9a4/README.md#L22
Default to `text` if no other value is given, but error and exit on non-supported values.
> Add ability to log in json

- README.md
- pkg/ingress/ingress.go
- pkg/kubelego/configure.go
- pkg/kubelego/kubelego.go
- pkg/kubelego/type.go
- pkg/kubelego_const/consts.go
- pkg/kubelego_const/interfaces.go
- pkg/mocks/kubelego.go
- pkg/mocks/mocks.go
- pkg/provider/nginx/nginx.go
Previously you're ingress provider and classes had to have the same name. These should be two different concepts and be used in combination.
For example if you have:
Ingress classes for nginx-internal and nginx-external but want them to both be provided by nginx then if you don't have the provider and class as two different concepts this isn't possible.
Below is an example ingress resource with the new annotation:
```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: svc-ing
namespace: some-namespace
annotations:
kubernetes.io/tls-acme: "true"
kubernetes.io/ingress.provider: "nginx"
kubernetes.io/ingress.class: "nginx-external"
ingress.kubernetes.io/ssl-redirect: "true"
spec:
tls:
- hosts:
- example.com
secretName: svc-tls
rules:
- host: example.com
http:
paths:
-
path: …
```
> Seperate concept of provider and class

- README.md
- pkg/ingress/ingress.go
- pkg/kubelego/kubelego.go
- pkg/kubelego_const/interfaces.go
- pkg/provider/nginx/nginx.go
This should solve a regression that causes the GCE ingress controller implementation to not work with manifests that don't explicitly set `kubernetes.io/ingress.provider: gce`. Without this change, these manifests would attempt to use the `nginx` provider.
This also solves a problem where the default supported ingress classes were not set correctly if not specified.
> Return ingress.class value for ingress.provider if not set

- pkg/provider/nginx/nginx.go
Without this PR the http-01 challenge (``/.well-known/acme-challenge``) fails in a setup where one has IPv6 (AAAA DNS record) set.
```
$ HOST=mysite.com; IP=212.123.123.123; curl -4 -L -I --resolve ${HOST}:80:${IP} --resolve ${HOST}:443:${IP} http://${HOST}/.well-known/acme-challenge/_selftest
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 03 Sep 2017 09:18:35 GMT
Content-Type: text/plain
Content-Length: 16
Strict-Transport-Security: max-age=15724800; includeSubDomains;
```
```
$ HOST=mysite.com; IP=2001:41e0:123:123::123; curl -6 -L -I --resolve ${HOST}:80:${IP} --resolve ${HOST}:443:${IP} http://${HOST}/.well-known/acme-challenge/_selftest
HTTP/1.1 403 Forbidden
Server: nginx
Date: Sun, 03 Sep 2017 09:18:39 GMT
Content-Type: text/html
Content-Length: 162
Strict-Transport-Security: …
```
> Whitelist IPv6 default route

- README.md
- pkg/ingress/ingress.go
- pkg/kubelego/kubelego.go
- pkg/kubelego_const/interfaces.go
- pkg/provider/nginx/nginx.go
This implementation should be backwards compatible as
it will default the provider to the same value as the class.
Relates to #233
> Reintroduce default ingress provider

- pkg/kubelego/kubelego.go
- pkg/kubelego/kubelego_test.go
Hi,
with this change a potential trailing slash is removed from the Lego Url.
Fixes #219 
Regards, Marc
> Remove trailing slash from Lego Url

- pkg/acme/cert_request.go
Before this change the selfcheck would succeed even if the remote
server was not this instance of kube-lego.
> Fix returning an error in selfcheck

- pkg/acme/acme.go
If kube-lego is behind some sort of caching server the caching server should be told not to cache any responses from kube-lego.
> Tell upstream caches to not cache

- README.md
- pkg/acme/acme_e2e_test.go
- pkg/acme/user.go
- pkg/kubelego/kubelego.go
- pkg/kubelego/kubelego_test.go
- pkg/kubelego/type.go
- pkg/kubelego_const/consts.go
- pkg/kubelego_const/interfaces.go
- pkg/mocks/mocks.go
With this change the RSA key size is made configurable.
The given keysize is checked to be a number and to be >= 512... not sure if there should be more checks?
Fixes #111
> Make RSA key size configurable

- pkg/ingress/tls.go
This PR adds a sanity check for `k8sExtensions.IngressTLS` resource. If the resource is malformed, no attempt to request a certificate would be made.
Here's an example of bad tls:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: test
annotations:
kubernetes.io/tls-acme: "true"
spec:
tls:
- hosts:
- test.example
- secretName: test-tls
rules:
- host: test.example
http:
paths:
- path: /
backend:
serviceName: test
servicePort: 80
```
Notice that `secretName` has a typo in front of it.
Such a yaml would be gladly accepted by k8s (which is a k8s problem, surely), but kube-lego makes it worse by first requesting and obtaining a certificate and then failing to store it anywhere.
> Added a sanity check before submitting CSR

- pkg/ingress/tls.go
- pkg/ingress/tls_suite_test.go
- pkg/secret/secret.go
`(i *Tls) Process()` function makes an extra `client.KubeClient().Secrets(namespace).Get(name, k8sMeta.GetOptions{})` call when a certificate needed for a given `Tls` object. The first call happens in `i.newCertNeeded` and the second call happens in `i.RequestCert`. There's already an effort for memoization of secret object, but it is buggy(I'm assuming that was not intentional - correct me if I'm wrong), i.e it does not set the initialized secret object to `t.secret` variable. The PR fixes the issue and adds test coverage.
> Memoize secret obj

- pkg/service/service.go
To workaround the issue with GCE here https://github.com/jetstack/kube-lego/issues/68 I want to setup manually service with selector and have kube-lego for each of my namespaces.
But kube-lego ignores the service annotation when it is updating the service. This adds check for kube-lego-managed=true annotation for updating existing service - similarly to the delete method already there.
> update only service with kube-lego-managed annotation

- pkg/kubelego/kubelego.go
- pkg/utils/useragent_roundtripper.go
This PR sets the user agent on the default HTTP roundtripper to help Letsencrypt diagnose abusive traffic patterns (reported here: https://github.com/jetstack/cert-manager/issues/407)
/cc @simonswine @jsha
> Set user agent on default http roundtripper

- pkg/ingress/ingress.go
- pkg/kubelego/configure.go
- pkg/kubelego/type.go
- pkg/kubelego/watch.go
This is in relation to https://github.com/jetstack/cert-manager/issues/407
From that issue:
> Based on the code in WatchEvents (https://github.com/jetstack/kube-lego/blob/master/pkg/kubelego/watch.go#L73) - it appears that whenever any Kubernetes Ingress resource is created, updated, or deleted, all Ingress resources are immediately scheduled for re-processing.
>
> Ingresses that already have a valid certificate will be skipped, but any user with a number of failing/invalid ingresses will make requests to LE APIs in an attempt to validate those ingresses.
>
> As part of those syncs, more updates will likely be made to ingresses, thus re-queuing these ingresses to be immediately reprocessed after the 'round' of processing ingresses fails.
>
> The good news is we do only process one Ingress …
> Adjust controller to process one ingress at a time. Use per-item rate limiting workqueue.

- pkg/kubelego/kubelego.go
- pkg/kubelego/watch.go
This fixes auto-renewal of certificates and exposes any future errors.
> Pass the ingress object, not the function to renew
